{% set version = "1.5.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ssbtools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/SSBtools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/SSBtools/SSBtools_{{ version }}.tar.gz
  sha256: f0fa8549d27fcea8ce013bac7f92dde71e0f9e9f068d8b176c324d1a3b514bd3

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-matrix
    - r-stringr
  run:
    - r-base
    - r-mass
    - r-matrix
    - r-stringr

test:
  commands:
    - $R -e "library('SSBtools')"           # [not win]
    - "\"%R%\" -e \"library('SSBtools')\""  # [win]

about:
  home: https://github.com/statisticsnorway/SSBtools
  license: MIT
  summary: Functions used by other packages from Statistics Norway are gathered. General data manipulation functions, and functions for hierarchical computations are included (Langsrud, 2020) <doi:10.13140/RG.2.2.27313.61283>. The hierarchy specification functions are useful within statistical disclosure control.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - RJMW

# Package: SSBtools
# Type: Package
# Title: Statistics Norway's Miscellaneous Tools
# Version: 1.4.8
# Date: 2023-06-23
# Authors@R: c(person("yvind", "Langsrud", role = c("aut", "cre"), email = "oyl@ssb.no"), person("Daniel", "Lupp", role = c("aut")), person("Bjrn-Helge", "Mevik", role = c("ctb")), person("Statistics Norway", role = "cph"))
# Depends: Matrix
# Imports: stringr, methods, MASS
# Description: Functions used by other packages from Statistics Norway are gathered. General data manipulation functions, and functions for hierarchical computations are included (Langsrud, 2020) <doi:10.13140/RG.2.2.27313.61283>. The hierarchy specification functions are useful within statistical disclosure control.
# License: MIT + file LICENSE
# URL: https://github.com/statisticsnorway/SSBtools
# BugReports: https://github.com/statisticsnorway/SSBtools/issues
# RoxygenNote: 7.2.3
# Encoding: UTF-8
# Suggests: testthat
# NeedsCompilation: no
# Packaged: 2023-06-23 05:46:23 UTC; oyl
# Author: yvind Langsrud [aut, cre], Daniel Lupp [aut], Bjrn-Helge Mevik [ctb], Statistics Norway [cph]
# Maintainer: yvind Langsrud <oyl@ssb.no>
# Repository: CRAN
# Date/Publication: 2023-06-23 06:30:02 UTC
